name: Release and Hash
description: Upload files to GitHub Release and attach file hash to asset urls.
inputs:
  tag:
    description: release tag
    required: true
  files:
    description: files to upload
    required: true
  repo:
    description: upload to which repo
    required: true
    default: ${{ github.repository }}
  notes:
    description: release notes
    required: false
    default: ''
outputs:
  urls:
    description: url to uploaded files, with sha256 as url fragment
    value: ${{ steps.hash.outputs.urls }}

runs:
  using: composite
  steps:
    - name: upload
      env:
        notes: ${{ inputs.notes }}
      run: |
        url=$(gh release -R ${{ inputs.repo }} view ${{ inputs.tag }} || exit 0)

        files=""
        for file in ${{ inputs.files }}; do
            files="$files$file "
        done

        if [[ $url != "" ]]; then
            echo "uploading $files"
            gh release -R ${{ inputs.repo }} edit   ${{ inputs.tag }} -n "$notes"
            gh release -R ${{ inputs.repo }} upload ${{ inputs.tag }} $files --clobber
        else
            echo "creating release with $files"
            gh release -R ${{ inputs.repo }} create ${{ inputs.tag }} $files -n "$notes"
        fi
      shell: bash

    - name: query urls
      id: query
      run: |
        sharp_list="#"
        for file in ${{ inputs.files }}; do
            sharp_list="$sharp_list$(basename $file)#"
        done
        filter=".assets[] | select( \"#\" + .name + \"#\" | inside(\"$sharp_list\") ) | .url"
        echo "::debug::filter"

        urls=$(gh release -R ${{ inputs.repo }} view ${{ inputs.tag }} --json assets -q "$filter")
        echo "urls=$(echo $urls | tr '\n' ' ')" >> $GITHUB_OUTPUT
      shell: bash

    - uses: JamzumSum/actions/url-attach-hash@master
      id: hash
      with:
        files: ${{ inputs.files }}
        urls: ${{ steps.query.outputs.urls }}
