name: Generate Changelog
description: Generate a changelog from the given start & end revspec.
inputs:
  start:
    description: start revspec
    required: true
  end:
    description: end revspec
    required: true
    default: HEAD
  tag:
    description: a tag for the "unreleased" changes
    required: false
    default: ""
  args:
    description: any other args
    required: false
    default: "-v"
outputs:
  changelog:
    description: generated changelog
    value: ${{ steps.git-cliff.outputs.content }}

runs:
  using: composite
  steps:
    - id: sha
      run: |
        if git rev-parse --verify refs/remotes/origin/${{ inputs.start }} >/dev/null 2>&1; then
          sha=$(git rev-parse --short refs/remotes/origin/${{ inputs.start }})
          echo "range=${sha}..${{ inputs.end }}" >> $GITHUB_OUTPUT
        else
          echo "::warning:: ${{ inputs.start }} not exist"
        fi
      shell: bash

    - name: set tag
      env:
        tag: ${{ inputs.tag }}
      run: |
        if [[ $tag = "" ]]; then
            version=$(sed -nr "s/^\s*version\s*=\s*\"(.*)\"/\1/p" pyproject.toml)
            echo "tag=$version" >> $GITHUB_ENV
        else
            echo "tag=$tag"
        fi
      shell: bash

    - name: Generate a changelog
      uses: orhun/git-cliff-action@v4
      id: git-cliff
      with:
        config: cliff.toml
        args: --strip header ${{ steps.sha.outputs.range }} --tag ${{ env.tag }} ${{ inputs.args }}
